version: '3.8'
services:
  galera1:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MARIADB_GALERA_CLUSTER_NAME: galera_cluster
      MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://galera1,galera2,galera3
      MARIADB_GALERA_NODE_NAME: galera1
      MARIADB_GALERA_SST_METHOD: rsync
    volumes: ['./infra/data/galera1:/var/lib/mysql']
    ports: ['3307:3306']
    networks: ['galera-net']

  galera2:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MARIADB_GALERA_CLUSTER_NAME: galera_cluster
      MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://galera1,galera2,galera3
      MARIADB_GALERA_NODE_NAME: galera2
      MARIADB_GALERA_SST_METHOD: rsync
    volumes: ['./infra/data/galera2:/var/lib/mysql']
    networks: ['galera-net']

  galera3:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MARIADB_GALERA_CLUSTER_NAME: galera_cluster
      MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://galera1,galera2,galera3
      MARIADB_GALERA_NODE_NAME: galera3
      MARIADB_GALERA_SST_METHOD: rsync
    volumes: ['./infra/data/galera3:/var/lib/mysql']
    networks: ['galera-net']

  order:
    build: ./services/order
    ports: ['3001:3001']
    depends_on: ['galera1','galera2','galera3']

  gateway:
    build: ./services/gateway
    ports: ['3000:3000']
    environment:
      ORDER_SERVICE_URL: http://order:3001
    depends_on: ['order']

networks:
  galera-net:
    driver: bridge
