version: "3.8"
services:
  galera1:
    image: mariadb:10.5
    container_name: galera1
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MARIADB_GALERA_CLUSTER_NAME: galera_cluster
      MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://galera1,galera2,galera3
      MARIADB_GALERA_NODE_NAME: galera1
      MARIADB_GALERA_SST_METHOD: rsync
    volumes:
      - ./data/galera1:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - galera-net

  galera2:
    image: mariadb:10.5
    container_name: galera2
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MARIADB_GALERA_CLUSTER_NAME: galera_cluster
      MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://galera1,galera2,galera3
      MARIADB_GALERA_NODE_NAME: galera2
      MARIADB_GALERA_SST_METHOD: rsync
    volumes:
      - ./data/galera2:/var/lib/mysql
    networks:
      - galera-net

  galera3:
    image: mariadb:10.5
    container_name: galera3
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MARIADB_GALERA_CLUSTER_NAME: galera_cluster
      MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://galera1,galera2,galera3
      MARIADB_GALERA_NODE_NAME: galera3
      MARIADB_GALERA_SST_METHOD: rsync
    volumes:
      - ./data/galera3:/var/lib/mysql
    networks:
      - galera-net

networks:
  galera-net:
    driver: bridge
