name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [order, gateway]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd services/${{ matrix.service }}
          npm ci

      - name: Lint service ${{ matrix.service }}
        run: |
          cd services/${{ matrix.service }}
          npm run lint

      - name: Test service ${{ matrix.service }}
        run: |
          cd services/${{ matrix.service }}
          npm test

      - name: Build Docker image for ${{ matrix.service }}
        run: docker build services/${{ matrix.service }} -t ${{ matrix.service }}-service:${{ github.sha }}
